lib/loan_service_web/router.ex
defmodule LoanServiceWeb.Router do
  use LoanServiceWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", LoanServiceWeb do
    pipe_through :browser

    get "/", LoanController, :new

    post "/", LoanController, :create
  end

  scope "/admin", LoanServiceWeb do
    pipe_through :browser

    get "/", AdminController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", LoanServiceWeb do
  #   pipe_through :api
  # end
end

lib/loan_service/application.ex
defmodule LoanService.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the Ecto repository
      LoanService.Repo,
      # Start the endpoint when the application starts
      LoanServiceWeb.Endpoint,
      # Starts a worker by calling: Test.Worker.start_link(arg)
      # {Test.Worker, arg},
      LoanService.Cache
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: LoanService.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    LoanServiceWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/loan_service/cache.ex
defmodule LoanService.Cache do
  @moduledoc false

  @module __MODULE__

  use GenServer

  import Ecto.Query

  alias LoanService.{LoanApplication, Repo}

  require Logger

  def start_link(_) do
    GenServer.start_link(@module, nil)
  end

  def get_minimum_amount(), do: :ets.lookup(:cache, :minimum_amount)[:minimum_amount]

  def update_minimum_amount(amount), do: :ets.insert(:cache, {:minimum_amount, amount})

  @impl true
  def init(_init_arg) do
    ets = :ets.new(:cache, [:named_table, :set, :public])

    amounts = Repo.all(from application in LoanApplication, select: application.amount)
    minimum_amount = Enum.min(amounts, fn -> 0 end)

    :ets.insert(ets, {:minimum_amount, minimum_amount})
    Logger.info("Cache initialized: #{minimum_amount}")
    {:ok, ets}
  end
end

lib/loan_service/engine.ex
defmodule LoanService.Engine do
  @moduledoc false

  alias LoanService.Cache

  def calculate_interest_rate(amount) do
    current_minimum = Cache.get_minimum_amount()

    cond do
      amount < current_minimum ->
        Cache.update_minimum_amount(amount)
        {:error, :rejected}

      prime?(amount) ->
        {:ok, 9.99}

      true ->
        {:ok, generate_random_interest(4, 12)}
    end
  end

  defp prime?(2), do: true

  defp prime?(num) do
    last =
      num
      |> :math.sqrt()
      |> Float.ceil()
      |> trunc

    notprime =
      2..last
      |> Enum.any?(fn a -> rem(num, a) == 0 end)

    !notprime
  end

  defp generate_random_interest(from, to) do
    rand_int = Enum.random((from * 100)..(to * 100))
    rand_int / 100
  end
end

lib/loan_service/loan_application.ex
defmodule LoanService.LoanApplication do
  use Ecto.Schema
  import Ecto.Changeset

  schema "loan_applications" do
    field :amount, :integer
    field :email, :string
    field :first_name, :string
    field :last_name, :string
    field :phone, :string

    timestamps()
  end

  @doc false
  def changeset(loan_application, attrs) do
    loan_application
    |> cast(attrs, [:amount, :first_name, :last_name, :phone, :email])
    |> validate_required([:amount, :first_name, :last_name, :phone, :email])
    |> validate_format(:email, ~r/@/)
    |> validate_number(:amount, greater_than: 0)
    |> validate_format(:phone, ~r/^[[:digit:]]+$/)
  end
end

lib/loan_service/loan_interest.ex
defmodule LoanService.LoanInterest do
  use Ecto.Schema
  import Ecto.Changeset

  schema "loan_interests" do
    field :rate, :float
    field :loan_application_id, :id

    timestamps()
  end

  @doc false
  def changeset(loan_interest, attrs) do
    loan_interest
    |> cast(attrs, [:rate, :loan_application_id])
    |> validate_required([:rate, :loan_application_id])
  end
end

lib/loan_service/repo.ex
defmodule LoanService.Repo do
  use Ecto.Repo,
    otp_app: :loan_service,
    adapter: Ecto.Adapters.Postgres
end

lib/loan_service_web/controllers/admin_controller.ex
defmodule LoanServiceWeb.AdminController do
  use LoanServiceWeb, :controller
  alias LoanService.{LoanApplication, LoanInterest, Repo}

  def index(conn, _params) do
    applications = Repo.all(LoanApplication)
    interests = Repo.all(LoanInterest)
    render(conn, "index.html", applications: applications, interests: interests)
  end
end

lib/loan_service_web/controllers/loan_controller.ex
defmodule LoanServiceWeb.LoanController do
  use LoanServiceWeb, :controller

  require Logger

  alias Ecto.Changeset
  alias LoanService.{Engine, LoanApplication, LoanInterest, Repo}

  def new(conn, _params) do
    loan_application = LoanApplication.changeset(%LoanApplication{}, %{})
    render(conn, "new.html", changeset: loan_application)
  end

  def create(conn, params) do
    loan_application = Map.get(params, "loan_application")
    changeset = LoanApplication.changeset(%LoanApplication{}, loan_application)
    Logger.debug(inspect(changeset))

    with true <- changeset.valid?,
         {:ok, amount} <- Changeset.fetch_change(changeset, :amount),
         {:ok, %{id: loan_application_id}} <- Repo.insert(changeset),
         {:ok, interest_rate} <- Engine.calculate_interest_rate(amount),
         {:ok, _} <- insert_interest_rate(interest_rate, loan_application_id) do
      render(conn, "offer.html", changeset: changeset, interest_rate: interest_rate)
    else
      false ->
        conn
        |> put_flash(:error, "Invalid Data")
        |> render("new.html", changeset: changeset)

      {:error, :rejected} ->
        render(conn, "rejection.html")
    end
  end

  defp insert_interest_rate(interest_rate, loan_application_id) do
    changeset =
      LoanInterest.changeset(
        %LoanInterest{},
        %{loan_application_id: loan_application_id, rate: interest_rate}
      )

    Logger.debug(inspect(changeset))

    Repo.insert(changeset)
  end
end

lib/loan_service_web/controllers/page_controller.ex
defmodule LoanServiceWeb.PageController do
  use LoanServiceWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/loan_service_web/views/admin_view.ex
defmodule LoanServiceWeb.AdminView do
  use LoanServiceWeb, :view

  def get_application_result(application, interests) do
    id = application.id

    interest =
      interests
      |> Enum.filter(fn interest -> interest.loan_application_id == id end)
      |> List.first()

    case interest do
      nil -> "REJ"
      interest -> interest.rate
    end
  end
end

lib/loan_service_web/views/error_view.ex
defmodule LoanServiceWeb.ErrorView do
  use LoanServiceWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/loan_service_web/views/layout_view.ex
defmodule LoanServiceWeb.LayoutView do
  use LoanServiceWeb, :view
end

lib/loan_service_web/views/loan_view.ex
defmodule LoanServiceWeb.LoanView do
  use LoanServiceWeb, :view

  alias Ecto.Changeset

  def get_key(changeset, key), do: Changeset.get_change(changeset, key)
end

lib/loan_service_web/views/page_view.ex
defmodule LoanServiceWeb.PageView do
  use LoanServiceWeb, :view
end

lib/loan_service_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>LoanService · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      
      <section class="container">
        <h1>Loan Service</h1>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/loan_service_web/templates/loan/new.html.eex
<%= form_for @changeset, Routes.loan_path(@conn, :create), fn f -> %>
  <label>
    Requested loan amount (in SEK): <%= number_input f, :amount %>
  </label>
  <label>
    First name: <%= text_input f, :first_name %>
  </label>
  <label>
    Last name: <%= text_input f, :last_name %>
  </label>
  <label>
    Phone number: <%= telephone_input f, :phone %>
  </label>
  <label>
    Email address: <%= email_input f, :email %>
  </label>
  

  <%= submit "Submit" %>
<% end %>

lib/loan_service_web/templates/loan/offer.html.eex
<section class="phx-hero">
    <h1>Offer!</h1>
    <h2> Interest rate: <%= @interest_rate %>%</h2>
</section>

<label>
    Requested loan amount (in SEK):
</label>
<p>
    <%= get_key(@changeset, :amount) %>
</p>
<label>
    First name:
</label>
<p>
    <%= get_key(@changeset, :first_name) %>
</p>
<label>
    Last name:
</label>
<p>
    <%= get_key(@changeset, :last_name) %>
</p>
<label>
    Phone number:
</label>
<p>
    <%= get_key(@changeset, :phone) %>
</p>
<label>
    Email address:
</label>
<p>
    <%= get_key(@changeset, :email) %>
</p>

lib/loan_service_web/templates/loan/rejection.html.eex
<section class="phx-hero">
    <meta http-equiv="refresh" content="3; url=/">
    <h1>Try Again!</h1>
</section>

lib/loan_service_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h1>
  <p>A productive web framework that<br/>does not compromise speed or maintainability.</p>
</section>

<section class="row">
  <article class="column">
    <h2>Resources</h2>
    <ul>
      <li>
        <a href="https://hexdocs.pm/phoenix/overview.html">Guides &amp; Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix/blob/v1.4/CHANGELOG.md">v1.4 Changelog</a>
      </li>
    </ul>
  </article>
  <article class="column">
    <h2>Help</h2>
    <ul>
      <li>
        <a href="https://elixirforum.com/c/phoenix-forum">Forum</a>
      </li>
      <li>
        <a href="https://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on Freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">Twitter @elixirphoenix</a>
      </li>
    </ul>
  </article>
</section>